### ISSUE TITLE
Sprint 2 review

### ISSUE THREAD

**Issue by katz0018** [no-wuckas/no-wuckas-app#19]
The team was able to successfully finish all the tasks in sprint 2 and we are all very satisfied with the outcome.

@thomasjbradley

**Comment by fkhan24** [comment]
We were able to work collaboratively via voice call and complete/review each individual task.

**Comment by hovski** [comment]
@thomasjbradley We completed all the tasks for Sprint 2 and were overall satisfied. As a team, we've talked about tweaking the Ui design slightly and improving a few button placements and page layouts. Other than that, we got our work finished as a team and everything went smoothly.

**Comment by katz0018** [comment]
We managed to finish all the tasks and are ready for sprint 3.

**Comment by nilababaei** [comment]
I believe that Sprint 2 went by very successfully. We completed all our tasks in a timely manner and worked very efficiently.

We did have some trouble when starting our work on the prototype. XD only allows one contributor at the same time. So we worked by sending inspiration for layouts to Annie where she developed the wireframe.

**Comment by thomasjbradley** [comment]
Don’t forget to move the cards to the "Done" column.
